#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# savotechnologies.com — Bluehost VPS one-shot provisioning (Ubuntu 24.04)
#
# Installs Node 22, PostgreSQL, Nginx, PM2, Certbot; deploys savo.v6
# (branch feat/admin-console) with a production database, admin user and
# production content mode; starts everything under PM2 + Nginx.
#
# Run as root on the VPS. Requires GIT_TOKEN in the environment
# (read access to theelitesherpas/dev.savotechnologies).
# Idempotent: safe to re-run.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

BRANCH="feat/admin-console"
APP_DIR="/var/www/savotechnologies"
LOG="/var/log/savo-setup.log"
exec > >(tee -a "$LOG") 2>&1

say() { echo -e "\n═══ $* ═══"; }

[ "$(id -u)" -eq 0 ] || { echo "Run as root"; exit 1; }
[ -n "${GIT_TOKEN:-}" ] || { echo "export GIT_TOKEN first"; exit 1; }

say "1/9 System packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y curl ca-certificates gnupg git nginx postgresql postgresql-contrib certbot python3-certbot-nginx

say "2/9 Node.js 22"
if ! command -v node >/dev/null || [ "$(node -v | cut -c2-3)" != "22" ]; then
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y nodejs
fi
node -v

# Safety swap for small VPS plans (build memory)
if [ "$(swapon --show | wc -l)" -eq 0 ]; then
  say "2b Swap (2GB) for build headroom"
  fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile
  grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

say "3/9 PM2"
npm install -g pm2@latest

say "4/9 PostgreSQL database"
GEN_DB_PASS="$(head -c 24 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 24)"
systemctl enable --now postgresql
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='savo'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE USER savo WITH ENCRYPTED PASSWORD '${GEN_DB_PASS}';"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='savo_prod'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE DATABASE savo_prod OWNER savo;"

say "5/9 Application code"
mkdir -p /var/www
if [ -d "$APP_DIR/.git" ]; then
  cd "$APP_DIR" && git fetch origin "$BRANCH" && git reset --hard "origin/$BRANCH"
else
  git clone -b "$BRANCH" "https://x-access-token:${GIT_TOKEN}@github.com/theelitesherpas/dev.savotechnologies.git" "$APP_DIR"
  cd "$APP_DIR" && git remote set-url origin https://github.com/theelitesherpas/dev.savotechnologies.git
fi
git -C "$APP_DIR" config --unset-all http.extraheader 2>/dev/null || true

say "6/9 Environment"
if [ ! -f "$APP_DIR/.env.production" ]; then
  GEN_SALT="$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)"
  GEN_ADMIN_PASS="$(head -c 16 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 16)Bh9"
  cat > "$APP_DIR/.env.production" <<ENV
# ── Production ─ savotechnologies.com (generated by server-setup.sh) ──
DATABASE_URL="postgresql://savo:${GEN_DB_PASS}@localhost:5432/savo_prod"
ENQUIRY_IP_SALT="${GEN_SALT}"
ADMIN_EMAIL="admin@savotechnologies.com"
ADMIN_PASSWORD="${GEN_ADMIN_PASS}"
NEXT_PUBLIC_SITE_URL="https://savotechnologies.com"
NEXT_PUBLIC_CONTENT_MODE="production"
NEXT_PUBLIC_INDEXABLE="true"
ENV
  chmod 600 "$APP_DIR/.env.production"
  cat > /root/savo-credentials.txt <<CREDS
SAVO PRODUCTION CREDENTIALS (keep safe)
──────────────────────────────────────
Admin panel:  https://savotechnologies.com/admin
Admin email:  admin@savotechnologies.com
Admin pass:   ${GEN_ADMIN_PASS}
DB user:      savo / ${GEN_DB_PASS} (local only, db savo_prod)
CREDS
  chmod 600 /root/savo-credentials.txt
fi

say "7/9 Dependencies + database schema"
cd "$APP_DIR"
cp .env.production .env 2>/dev/null || true
npm ci --include=dev
set -a; . ./.env.production; set +a
npx prisma db push
node scripts/seed.mjs

say "8/9 Production build (CONTENT_MODE=production, indexable)"
NEXT_PUBLIC_CONTENT_MODE=production NEXT_PUBLIC_INDEXABLE=true npm run build

say "9/9 PM2 + Nginx"
pm2 delete savo 2>/dev/null || true
pm2 start npm --name savo --cwd "$APP_DIR" -- run start
pm2 startup systemd -u root --hp /root >/dev/null 2>&1 || true
pm2 save

cat > /etc/nginx/sites-available/savotechnologies <<NGINX
server {
    listen 80;
    listen [::]:80;
    server_name savotechnologies.com www.savotechnologies.com 50.6.44.47;

    client_max_body_size 15m;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript image/svg+xml;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 120s;
    }
}
NGINX
ln -sf /etc/nginx/sites-available/savotechnologies /etc/nginx/sites-enabled/savotechnologies
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx

echo ""
echo "════════════════════════ SETUP COMPLETE ════════════════════════"
echo " App running under PM2 (app name: savo) on port 3000"
echo " Nginx serving on port 80 (HTTP works now: http://50.6.44.47)"
echo " Admin credentials saved at /root/savo-credentials.txt"
echo ""
echo " NEXT — point the domain (Hostinger DNS):"
echo "   A      @   → 50.6.44.47"
echo "   CNAME  www → savotechnologies.com"
echo ""
echo " Then run the SSL step:"
echo "   certbot --nginx -d savotechnologies.com -d www.savotechnologies.com \\"
echo "     --non-interactive --agree-tos --redirect -m hello@savotechnologies.com"
echo "════════════════════════════════════════════════════════════════"
